### ISSUE TITLE
[home page] Establish standard for sticky page header component

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#91] opened 2018-05-07 18:03 UTC
The new home page may feature a sticky header for downloading Firefox. This is a task to discuss creation of a reusable sticky header component that may be reused for different purposes.

**Comment by amychurchwell** [comment] 2019-07-17 18:12
If the whether the header was sticky or not was a variant, we could also use this component for pages that omit the nav like whatsnew:
![Screen Shot 2019-07-17 at 11 10 46 AM](https://user-images.githubusercontent.com/30483988/61399770-aab9db80-a883-11e9-9bc9-2f635ce8b515.png)

**Comment by amychurchwell** [comment] 2019-07-17 18:15
Sticky variant would include dismiss 'x'
![Screen Shot 2019-07-17 at 11 13 02 AM](https://user-images.githubusercontent.com/30483988/61399881-e8b6ff80-a883-11e9-8ccf-4aaa7e7f20ab.png)

Options:
- Logo
- Logo text
- Center content
- CTA
- Stickiness

**Comment by hoosteeno** [comment] 2020-03-23 21:50
This is a duplicate of a more recent, more complete issue. 

https://github.com/mozilla/bedrock/issues/8676

**Closed by hoosteeno** 2020-03-23 21:50 UTC
Labels: Blocked ✋, Design 🎨, Discussion :bike:, P1
