### ISSUE TITLE
Add Firefox themed text input

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#432] opened 2019-07-19 16:08 UTC
See: https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit?usp=sharing

Normal Text Input | Default
-- | --
Text Input, Hover | When user hovers over text box, a hover displays.
Text Input, Focus | When the user has selected the text box, a focus selection appears.
Text Input, Error | When there is an error in the text box element, an error state shows.
Text Input, Success | When the user is successful in enter an item in a text box, a success state shows.
Text Input, Disabled | There is a disabled state for the text box.

**Comment by craigcook** [comment] 2019-07-22 15:28
This is essentially a dupe of #430 we don't really need to separate field-with-placeholder from field-without-placeholder, they're the same element.

**Closed by craigcook** 2019-07-22 15:28 UTC
Labels: Dev ⚙️
